apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: fruits-processor-to-knative
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: fruits-processor
    properties:
      topic: "fruits"
      brokers: "my-cluster-kafka-bootstrap.kafka:9092"
  sink:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: default